import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import LeftSidebar from '@/components/side/left-sidebar';
import LeftSidebarSm from '@/components/side/left-sidebar-sm';
import Providers from '@/lib/providers/providers';

const font = Roboto({ subsets: ['latin'], weight: ['700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={font.className}>
        <Providers>
          <div className="flex">
            <LeftSidebar className="hidden md:block" />
            <LeftSidebarSm className="block md:hidden" />
            <div className="flex-1">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
